[mgr]
cwd = { fg = "#94e2d5" }

hovered         = { fg = "#1e1e2e", bg = "#b4befe" }
preview_hovered = { fg = "#1e1e2e", bg = "#cdd6f4" }

find_keyword    = { fg = "#f9e2af", italic = true }
find_position   = { fg = "#f5c2e7", bg = "reset", italic = true }

marker_copied   = { fg = "#a6e3a1", bg = "#a6e3a1" }
marker_cut      = { fg = "#f38ba8", bg = "#f38ba8" }
marker_marked   = { fg = "#94e2d5", bg = "#94e2d5" }
marker_selected = { fg = "#b4befe", bg = "#b4befe" }

count_copied    = { fg = "#1e1e2e", bg = "#a6e3a1" }
count_cut       = { fg = "#1e1e2e", bg = "#f38ba8" }
count_selected  = { fg = "#1e1e2e", bg = "#b4befe" }

border_symbol   = "│"
border_style    = { fg = "#7f849c" }

syntect_theme   = "~/.config/yazi/Catppuccin-mocha.tmTheme"

[tabs]
active    = { fg = "#1e1e2e", bg = "#cdd6f4" }
inactive  = { fg = "#cdd6f4", bg = "#45475a" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
normal_main = { fg = "#1e1e2e", bg = "#b4befe", bold = true }
normal_alt  = { fg = "#b4befe", bg = "#313244" }

select_main = { fg = "#1e1e2e", bg = "#a6e3a1", bold = true }
select_alt  = { fg = "#a6e3a1", bg = "#313244" }

unset_main  = { fg = "#1e1e2e", bg = "#f2cdcd", bold = true }
unset_alt   = { fg = "#f2cdcd", bg = "#313244" }

[status]
sep_left        = { open = "", close = "" }
sep_right       = { open = "", close = "" }

progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#89b4fa", bg = "#45475a" }
progress_error  = { fg = "#f38ba8", bg = "#45475a" }

perm_type       = { fg = "#89b4fa" }
perm_read       = { fg = "#f9e2af" }
perm_write      = { fg = "#f38ba8" }
perm_exec       = { fg = "#a6e3a1" }
perm_sep        = { fg = "#7f849c" }

[input]
border   = { fg = "#b4befe" }
title    = {}
value    = {}
selected = { reversed = true }

[pick]
border   = { fg = "#b4befe" }
active   = { fg = "#f5c2e7" }
inactive = {}

[confirm]
border   = { fg = "#b4befe" }
title    = { fg = "#b4befe" }
content  = {}
list     = {}
btn_yes  = { reversed = true }
btn_no   = {}

[cmp]
border   = { fg = "#b4befe" }

[tasks]
border   = { fg = "#b4befe" }
title    = {}
hovered  = { underline = true }

[which]
mask            = { bg = "#313244" }
cand            = { fg = "#94e2d5" }
rest            = { fg = "#9399b2" }
desc            = { fg = "#f5c2e7" }
separator       = "  "
separator_style = { fg = "#585b70" }

[help]
on      = { fg = "#94e2d5" }
run     = { fg = "#f5c2e7" }
desc    = { fg = "#9399b2" }
hovered = { bg = "#585b70", bold = true }
footer  = { fg = "#cdd6f4", bg = "#45475a" }

[notify]
title_info  = { fg = "#94e2d5" }
title_warn  = { fg = "#f9e2af" }
title_error = { fg = "#f38ba8" }

[filetype]
rules = [
  { mime = "image/*", fg = "#94e2d5" },
  { mime = "{audio,video}/*", fg = "#f9e2af" },
  { mime = "application/*zip", fg = "#f5c2e7" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#f5c2e7" },
  { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },
  { url = "*", fg = "#cdd6f4" },
  { url = "*/", fg = "#b4befe" }
]

[icon]
files = [
  { name = "kritadisplayrc", text = "", fg = "#cba6f7" },
  { name = ".gtkrc-2.0", text = "", fg = "#f5e0dc" },
  { name = "bspwmrc", text = "", fg = "#313244" },
  { name = "webpack", text = "󰜫", fg = "#74c7ec" },
  { name = "tsconfig.json", text = "", fg = "#74c7ec" },
  { name = ".vimrc", text = "", fg = "#a6e3a1" },
  { name = "gemfile$", text = "", fg = "#313244" },
  { name = "xmobarrc", text = "", fg = "#f38ba8" },
  { name = "avif", text = "", fg = "#7f849c" },
  { name = "fp-info-cache", text = "", fg = "#f5e0dc" },
  { name = ".zshrc", text = "", fg = "#a6e3a1" },
  { name = "robots.txt", text = "󰚩", fg = "#6c7086" },
  { name = "dockerfile", text = "󰡨", fg = "#89b4fa" },
  { name = ".git-blame-ignore-revs", text = "", fg = "#fab387" },
  { name = ".nvmrc", text = "", fg = "#a6e3a1" },
  { name = "hyprpaper.conf", text = "", fg = "#74c7ec" },
  { name = ".prettierignore", text = "", fg = "#89b4fa" },
  { name = "rakefile", text = "", fg = "#313244" },
  { name = "code_of_conduct", text = "", fg = "#f38ba8" },
  { name = "cmakelists.txt", text = "", fg = "#cdd6f4" },
  { name = ".env", text = "", fg = "#f9e2af" },
  { name = "copying.lesser", text = "", fg = "#f9e2af" },
  { name = "readme", text = "󰂺", fg = "#f5e0dc" },
  { name = "settings.gradle", text = "", fg = "#585b70" },
  { name = "gruntfile.coffee", text = "", fg = "#fab387" },
  { name = ".eslintignore", text = "", fg = "#585b70" },
  { name = "kalgebrarc", text = "", fg = "#89b4fa" },
  { name = "kdenliverc", text = "", fg = "#89b4fa" },
  { name = ".prettierrc.cjs", text = "", fg = "#89b4fa" },
  { name = "cantorrc", text = "", fg = "#89b4fa" },
  { name = "rmd", text = "", fg = "#74c7ec" },
  { name = "vagrantfile$", text = "", fg = "#6c7086" },
  { name = ".Xauthority", text = "", fg = "#fab387" },
  { name = "prettier.config.ts", text = "", fg = "#89b4fa" },
  { name = "node_modules", text = "", fg = "#f38ba8" },
  { name = ".prettierrc.toml", text = "", fg = "#89b4fa" },
  { name = "build.zig.zon", text = "", fg = "#fab387" },
  { name = ".ds_store", text = "", fg = "#45475a" },
  { name = "PKGBUILD", text = "", fg = "#89b4fa" },
  { name = ".prettierrc", text = "", fg = "#89b4fa" },
  { name = ".bash_profile", text = "", fg = "#a6e3a1" },
  { name = ".npmignore", text = "", fg = "#f38ba8" },
  { name = ".mailmap", text = "󰊢", fg = "#fab387" },
  { name = ".codespellrc", text = "󰓆", fg = "#a6e3a1" },
  { name = "svelte.config.js", text = "", fg = "#fab387" },
  { name = "eslint.config.ts", text = "", fg = "#585b70" },
  { name = "config", text = "", fg = "#7f849c" },
  { name = ".gitlab-ci.yml", text = "", fg = "#fab387" },
  { name = ".gitconfig", text = "", fg = "#fab387" },
  { name = "_gvimrc", text = "", fg = "#a6e3a1" },
  { name = ".xinitrc", text = "", fg = "#fab387" },
  { name = "checkhealth", text = "󰓙", fg = "#89b4fa" },
  { name = "sxhkdrc", text = "", fg = "#313244" },
  { name = ".bashrc", text = "", fg = "#a6e3a1" },
  { name = "tailwind.config.mjs", text = "󱏿", fg = "#74c7ec" },
  { name = "ext_typoscript_setup.txt", text = "", fg = "#fab387" },
  { name = "commitlint.config.ts", text = "󰜘", fg = "#94e2d5" },
  { name = "py.typed", text = "", fg = "#f9e2af" },
  { name = ".nanorc", text = "", fg = "#313244" },
  { name = "commit_editmsg", text = "", fg = "#fab387" },
  { name = ".luaurc", text = "", fg = "#89b4fa" },
  { name = "fp-lib-table", text = "", fg = "#f5e0dc" },
  { name = ".editorconfig", text = "", fg = "#f5e0dc" },
  { name = "justfile", text = "", fg = "#7f849c" },
  { name = "kdeglobals", text = "", fg = "#89b4fa" },
  { name = "license.md", text = "", fg = "#f9e2af" },
  { name = ".clang-format", text = "", fg = "#7f849c" },
  { name = "docker-compose.yaml", text = "󰡨", fg = "#89b4fa" },
  { name = "copying", text = "", fg = "#f9e2af" },
  { name = "go.mod", text = "", fg = "#74c7ec" },
  { name = "lxqt.conf", text = "", fg = "#89b4fa" },
  { name = "brewfile", text = "", fg = "#313244" },
  { name = "gulpfile.coffee", text = "", fg = "#f38ba8" },
  { name = ".dockerignore", text = "󰡨", fg = "#89b4fa" },
  { name = ".settings.json", text = "", fg = "#6c7086" },
  { name = "tailwind.config.js", text = "󱏿", fg = "#74c7ec" },
  { name = ".clang-tidy", text = "", fg = "#7f849c" },
  { name = ".gvimrc", text = "", fg = "#a6e3a1" },
  { name = "nuxt.config.cjs", text = "󱄆", fg = "#a6e3a1" },
  { name = "xsettingsd.conf", text = "", fg = "#fab387" },
  { name = "nuxt.config.js", text = "󱄆", fg = "#a6e3a1" },
  { name = "eslint.config.cjs", text = "", fg = "#585b70" },
  { name = "sym-lib-table", text = "", fg = "#f5e0dc" },
  { name = ".condarc", text = "", fg = "#a6e3a1" },
  { name = "xmonad.hs", text = "", fg = "#f38ba8" },
  { name = "tmux.conf", text = "", fg = "#a6e3a1" },
  { name = "xmobarrc.hs", text = "", fg = "#f38ba8" },
  { name = ".prettierrc.yaml", text = "", fg = "#89b4fa" },
  { name = ".pre-commit-config.yaml", text = "󰛢", fg = "#fab387" },
  { name = "i3blocks.conf", text = "", fg = "#f5e0dc" },
  { name = "xorg.conf", text = "", fg = "#fab387" },
  { name = ".zshenv", text = "", fg = "#a6e3a1" },
  { name = "vlcrc", text = "󰕼", fg = "#fab387" },
  { name = "license", text = "", fg = "#f9e2af" },
  { name = "unlicense", text = "", fg = "#f9e2af" },
  { name = "tmux.conf.local", text = "", fg = "#a6e3a1" },
  { name = ".SRCINFO", text = "󰣇", fg = "#89b4fa" },
  { name = "tailwind.config.ts", text = "󱏿", fg = "#74c7ec" },
  { name = "security.md", text = "󰒃", fg = "#bac2de" },
  { name = "security", text = "󰒃", fg = "#bac2de" },
  { name = ".eslintrc", text = "", fg = "#585b70" },
  { name = "gradle.properties", text = "", fg = "#585b70" },
  { name = "code_of_conduct.md", text = "", fg = "#f38ba8" },
  { name = "PrusaSlicerGcodeViewer.ini", text = "", fg = "#fab387" },
  { name = "PrusaSlicer.ini", text = "", fg = "#fab387" },
  { name = "procfile", text = "", fg = "#7f849c" },
  { name = "mpv.conf", text = "", fg = "#1e1e2e" },
  { name = ".prettierrc.json5", text = "", fg = "#89b4fa" },
  { name = "i3status.conf", text = "", fg = "#f5e0dc" },
  { name = "prettier.config.mjs", text = "", fg = "#89b4fa" },
  { name = ".pylintrc", text = "", fg = "#7f849c" },
  { name = "prettier.config.cjs", text = "", fg = "#89b4fa" },
  { name = ".luacheckrc", text = "", fg = "#89b4fa" },
  { name = "containerfile", text = "󰡨", fg = "#89b4fa" },
  { name = "eslint.config.mjs", text = "", fg = "#585b70" },
  { name = "gruntfile.js", text = "", fg = "#fab387" },
  { name = "bun.lockb", text = "", fg = "#f5e0dc" },
  { name = ".gitattributes", text = "", fg = "#fab387" },
  { name = "gruntfile.ts", text = "", fg = "#fab387" },
  { name = "pom.xml", text = "", fg = "#313244" },
  { name = "favicon.ico", text = "", fg = "#f9e2af" },
  { name = "package-lock.json", text = "", fg = "#313244" },
  { name = "build", text = "", fg = "#a6e3a1" },
  { name = "package.json", text = "", fg = "#f38ba8" },
  { name = "nuxt.config.ts", text = "󱄆", fg = "#a6e3a1" },
  { name = "nuxt.config.mjs", text = "󱄆", fg = "#a6e3a1" },
  { name = "mix.lock", text = "", fg = "#7f849c" },
  { name = "makefile", text = "", fg = "#7f849c" },
  { name = "gulpfile.js", text = "", fg = "#f38ba8" },
  { name = "lxde-rc.xml", text = "", fg = "#9399b2" },
  { name = "kritarc", text = "", fg = "#cba6f7" },
  { name = "gtkrc", text = "", fg = "#f5e0dc" },
  { name = "ionic.config.json", text = "", fg = "#89b4fa" },
  { name = ".prettierrc.mjs", text = "", fg = "#89b4fa" },
  { name = ".prettierrc.yml", text = "", fg = "#89b4fa" },
  { name = ".npmrc", text = "", fg = "#f38ba8" },
  { name = "weston.ini", text = "", fg = "#f9e2af" },
  { name = "gulpfile.babel.js", text = "", fg = "#f38ba8" },
  { name = "i18n.config.ts", text = "󰗊", fg = "#7f849c" },
  { name = "commitlint.config.js", text = "󰜘", fg = "#94e2d5" },
  { name = ".gitmodules", text = "", fg = "#fab387" },
  { name = "gradle-wrapper.properties", text = "", fg = "#585b70" },
  { name = "hypridle.conf", text = "", fg = "#74c7ec" },
  { name = "vercel.json", text = "▲", fg = "#f5e0dc" },
  { name = "hyprlock.conf", text = "", fg = "#74c7ec" },
  { name = "go.sum", text = "", fg = "#74c7ec" },
  { name = "kdenlive-layoutsrc", text = "", fg = "#89b4fa" },
  { name = "gruntfile.babel.js", text = "", fg = "#fab387" },
  { name = "compose.yml", text = "󰡨", fg = "#89b4fa" },
  { name = "i18n.config.js", text = "󰗊", fg = "#7f849c" },
  { name = "readme.md", text = "󰂺", fg = "#f5e0dc" },
  { name = "gradlew", text = "", fg = "#585b70" },
  { name = "go.work", text = "", fg = "#74c7ec" },
  { name = "gulpfile.ts", text = "", fg = "#f38ba8" },
  { name = "gnumakefile", text = "", fg = "#7f849c" },
  { name = "FreeCAD.conf", text = "", fg = "#f38ba8" },
  { name = "compose.yaml", text = "󰡨", fg = "#89b4fa" },
  { name = "eslint.config.js", text = "", fg = "#585b70" },
  { name = "hyprland.conf", text = "", fg = "#74c7ec" },
  { name = "docker-compose.yml", text = "󰡨", fg = "#89b4fa" },
  { name = "groovy", text = "", fg = "#585b70" },
  { name = "QtProject.conf", text = "", fg = "#a6e3a1" },
  { name = "platformio.ini", text = "", fg = "#fab387" },
  { name = "build.gradle", text = "", fg = "#585b70" },
  { name = ".nuxtrc", text = "󱄆", fg = "#a6e3a1" },
  { name = "_vimrc", text = "", fg = "#a6e3a1" },
  { name = ".zprofile", text = "", fg = "#a6e3a1" },
  { name = ".xsession", text = "", fg = "#fab387" },
  { name = "prettier.config.js", text = "", fg = "#89b4fa" },
  { name = ".babelrc", text = "", fg = "#f9e2af" },
  { name = "workspace", text = "", fg = "#a6e3a1" },
  { name = ".prettierrc.json", text = "", fg = "#89b4fa" },
  { name = ".prettierrc.js", text = "", fg = "#89b4fa" },
  { name = ".Xresources", text = "", fg = "#fab387" },
  { name = ".gitignore", text = "", fg = "#fab387" },
  { name = ".justfile", text = "", fg = "#7f849c" },
]
exts = [
  { name = "otf", text = "", fg = "#f5e0dc" },
  { name = "import", text = "", fg = "#f5e0dc" },
  { name = "krz", text = "", fg = "#cba6f7" },
  { name = "adb", text = "", fg = "#94e2d5" },
  { name = "ttf", text = "", fg = "#f5e0dc" },
  { name = "webpack", text = "󰜫", fg = "#74c7ec" },
  { name = "dart", text = "", fg = "#585b70" },
  { name = "vsh", text = "", fg = "#7f849c" },
  { name = "doc", text = "󰈬", fg = "#585b70" },
  { name = "zsh", text = "", fg = "#a6e3a1" }
]
